# Site settings
title: DB ML
subtitle: Deep Learning Consulting
email: philkuz [at] dbml.io
description: Deep Learning Consulting Firm
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dbml.io" # the base hostname & protocol for your site
author: "Phillip Kuznetsov"

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/db-ml
pinterest_url:
slack_url:

# Build settings
markdown: kramdown
